### ISSUE TITLE
Blocked or something

### ISSUE THREAD

**Issue by FurryDaniel** [sentanos/ProxyService#2]
![image](https://user-images.githubusercontent.com/55887183/147862464-7b0927f3-7132-4cd1-b359-0f8e1c2a706f.png)
I am unable create it so there is way can fix

**Comment by sentanos** [comment]
Unfortunately Heroku has blocked the proxy on their platform for whatever reason. There's nothing I can do, you will have to look for alternative places to host the proxy.

**Comment by Hyderite** [comment]
Actually, there is a way to fix that error! Check out this youtube video: https://www.youtube.com/watch?v=WFlOJ5dBTNk
