### ISSUE TITLE
Heroku (Item could not be created) Error

### ISSUE THREAD

**Issue by danielk0101** [sentanos/ProxyService#6]
![image](https://user-images.githubusercontent.com/99068805/152633118-806352a4-728e-47d6-9af1-f6b8d4a57d6b.png)
It shows me that error sadly :(

**Comment by sentanos** [comment]
Duplicate of #2

**Comment by Hyderite** [comment]
Actually, there is a way to fix that error! Check out this youtube video: https://www.youtube.com/watch?v=WFlOJ5dBTNk
